// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package main

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIHub creates a new instance of MockIHub. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIHub(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIHub {
	mock := &MockIHub{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIHub is an autogenerated mock type for the IHub type
type MockIHub struct {
	mock.Mock
}

type MockIHub_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIHub) EXPECT() *MockIHub_Expecter {
	return &MockIHub_Expecter{mock: &_m.Mock}
}

// Broadcast provides a mock function for the type MockIHub
func (_mock *MockIHub) Broadcast(msg any) {
	_mock.Called(msg)
	return
}

// MockIHub_Broadcast_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Broadcast'
type MockIHub_Broadcast_Call struct {
	*mock.Call
}

// Broadcast is a helper method to define mock.On call
//   - msg any
func (_e *MockIHub_Expecter) Broadcast(msg interface{}) *MockIHub_Broadcast_Call {
	return &MockIHub_Broadcast_Call{Call: _e.mock.On("Broadcast", msg)}
}

func (_c *MockIHub_Broadcast_Call) Run(run func(msg any)) *MockIHub_Broadcast_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIHub_Broadcast_Call) Return() *MockIHub_Broadcast_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIHub_Broadcast_Call) RunAndReturn(run func(msg any)) *MockIHub_Broadcast_Call {
	_c.Run(run)
	return _c
}

// GetRoundCh provides a mock function for the type MockIHub
func (_mock *MockIHub) GetRoundCh() chan *Round {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRoundCh")
	}

	var r0 chan *Round
	if returnFunc, ok := ret.Get(0).(func() chan *Round); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan *Round)
		}
	}
	return r0
}

// MockIHub_GetRoundCh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoundCh'
type MockIHub_GetRoundCh_Call struct {
	*mock.Call
}

// GetRoundCh is a helper method to define mock.On call
func (_e *MockIHub_Expecter) GetRoundCh() *MockIHub_GetRoundCh_Call {
	return &MockIHub_GetRoundCh_Call{Call: _e.mock.On("GetRoundCh")}
}

func (_c *MockIHub_GetRoundCh_Call) Run(run func()) *MockIHub_GetRoundCh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIHub_GetRoundCh_Call) Return(roundCh chan *Round) *MockIHub_GetRoundCh_Call {
	_c.Call.Return(roundCh)
	return _c
}

func (_c *MockIHub_GetRoundCh_Call) RunAndReturn(run func() chan *Round) *MockIHub_GetRoundCh_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRound provides a mock function for the type MockIHub
func (_mock *MockIHub) UpdateRound(r *Round) {
	_mock.Called(r)
	return
}

// MockIHub_UpdateRound_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRound'
type MockIHub_UpdateRound_Call struct {
	*mock.Call
}

// UpdateRound is a helper method to define mock.On call
//   - r *Round
func (_e *MockIHub_Expecter) UpdateRound(r interface{}) *MockIHub_UpdateRound_Call {
	return &MockIHub_UpdateRound_Call{Call: _e.mock.On("UpdateRound", r)}
}

func (_c *MockIHub_UpdateRound_Call) Run(run func(r *Round)) *MockIHub_UpdateRound_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Round
		if args[0] != nil {
			arg0 = args[0].(*Round)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIHub_UpdateRound_Call) Return() *MockIHub_UpdateRound_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIHub_UpdateRound_Call) RunAndReturn(run func(r *Round)) *MockIHub_UpdateRound_Call {
	_c.Run(run)
	return _c
}

// NewMockIRNGManager creates a new instance of MockIRNGManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIRNGManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIRNGManager {
	mock := &MockIRNGManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIRNGManager is an autogenerated mock type for the IRNGManager type
type MockIRNGManager struct {
	mock.Mock
}

type MockIRNGManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIRNGManager) EXPECT() *MockIRNGManager_Expecter {
	return &MockIRNGManager_Expecter{mock: &_m.Mock}
}

// CommitFor provides a mock function for the type MockIRNGManager
func (_mock *MockIRNGManager) CommitFor(roundID string) string {
	ret := _mock.Called(roundID)

	if len(ret) == 0 {
		panic("no return value specified for CommitFor")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(roundID)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockIRNGManager_CommitFor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CommitFor'
type MockIRNGManager_CommitFor_Call struct {
	*mock.Call
}

// CommitFor is a helper method to define mock.On call
//   - roundID string
func (_e *MockIRNGManager_Expecter) CommitFor(roundID interface{}) *MockIRNGManager_CommitFor_Call {
	return &MockIRNGManager_CommitFor_Call{Call: _e.mock.On("CommitFor", roundID)}
}

func (_c *MockIRNGManager_CommitFor_Call) Run(run func(roundID string)) *MockIRNGManager_CommitFor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIRNGManager_CommitFor_Call) Return(s string) *MockIRNGManager_CommitFor_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockIRNGManager_CommitFor_Call) RunAndReturn(run func(roundID string) string) *MockIRNGManager_CommitFor_Call {
	_c.Call.Return(run)
	return _c
}

// PickWinnerIndex provides a mock function for the type MockIRNGManager
func (_mock *MockIRNGManager) PickWinnerIndex(seed string, r *Round, n int) (int, error) {
	ret := _mock.Called(seed, r, n)

	if len(ret) == 0 {
		panic("no return value specified for PickWinnerIndex")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, *Round, int) (int, error)); ok {
		return returnFunc(seed, r, n)
	}
	if returnFunc, ok := ret.Get(0).(func(string, *Round, int) int); ok {
		r0 = returnFunc(seed, r, n)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(string, *Round, int) error); ok {
		r1 = returnFunc(seed, r, n)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIRNGManager_PickWinnerIndex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PickWinnerIndex'
type MockIRNGManager_PickWinnerIndex_Call struct {
	*mock.Call
}

// PickWinnerIndex is a helper method to define mock.On call
//   - seed string
//   - r *Round
//   - n int
func (_e *MockIRNGManager_Expecter) PickWinnerIndex(seed interface{}, r interface{}, n interface{}) *MockIRNGManager_PickWinnerIndex_Call {
	return &MockIRNGManager_PickWinnerIndex_Call{Call: _e.mock.On("PickWinnerIndex", seed, r, n)}
}

func (_c *MockIRNGManager_PickWinnerIndex_Call) Run(run func(seed string, r *Round, n int)) *MockIRNGManager_PickWinnerIndex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *Round
		if args[1] != nil {
			arg1 = args[1].(*Round)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIRNGManager_PickWinnerIndex_Call) Return(n1 int, err error) *MockIRNGManager_PickWinnerIndex_Call {
	_c.Call.Return(n1, err)
	return _c
}

func (_c *MockIRNGManager_PickWinnerIndex_Call) RunAndReturn(run func(seed string, r *Round, n int) (int, error)) *MockIRNGManager_PickWinnerIndex_Call {
	_c.Call.Return(run)
	return _c
}

// SeedFor provides a mock function for the type MockIRNGManager
func (_mock *MockIRNGManager) SeedFor(roundID string) string {
	ret := _mock.Called(roundID)

	if len(ret) == 0 {
		panic("no return value specified for SeedFor")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(roundID)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockIRNGManager_SeedFor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SeedFor'
type MockIRNGManager_SeedFor_Call struct {
	*mock.Call
}

// SeedFor is a helper method to define mock.On call
//   - roundID string
func (_e *MockIRNGManager_Expecter) SeedFor(roundID interface{}) *MockIRNGManager_SeedFor_Call {
	return &MockIRNGManager_SeedFor_Call{Call: _e.mock.On("SeedFor", roundID)}
}

func (_c *MockIRNGManager_SeedFor_Call) Run(run func(roundID string)) *MockIRNGManager_SeedFor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIRNGManager_SeedFor_Call) Return(s string) *MockIRNGManager_SeedFor_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockIRNGManager_SeedFor_Call) RunAndReturn(run func(roundID string) string) *MockIRNGManager_SeedFor_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIRoundManager creates a new instance of MockIRoundManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIRoundManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIRoundManager {
	mock := &MockIRoundManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIRoundManager is an autogenerated mock type for the IRoundManager type
type MockIRoundManager struct {
	mock.Mock
}

type MockIRoundManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIRoundManager) EXPECT() *MockIRoundManager_Expecter {
	return &MockIRoundManager_Expecter{mock: &_m.Mock}
}

// GenerateRound provides a mock function for the type MockIRoundManager
func (_mock *MockIRoundManager) GenerateRound() *Round {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GenerateRound")
	}

	var r0 *Round
	if returnFunc, ok := ret.Get(0).(func() *Round); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Round)
		}
	}
	return r0
}

// MockIRoundManager_GenerateRound_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateRound'
type MockIRoundManager_GenerateRound_Call struct {
	*mock.Call
}

// GenerateRound is a helper method to define mock.On call
func (_e *MockIRoundManager_Expecter) GenerateRound() *MockIRoundManager_GenerateRound_Call {
	return &MockIRoundManager_GenerateRound_Call{Call: _e.mock.On("GenerateRound")}
}

func (_c *MockIRoundManager_GenerateRound_Call) Run(run func()) *MockIRoundManager_GenerateRound_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIRoundManager_GenerateRound_Call) Return(round *Round) *MockIRoundManager_GenerateRound_Call {
	_c.Call.Return(round)
	return _c
}

func (_c *MockIRoundManager_GenerateRound_Call) RunAndReturn(run func() *Round) *MockIRoundManager_GenerateRound_Call {
	_c.Call.Return(run)
	return _c
}

// ScheduleRound provides a mock function for the type MockIRoundManager
func (_mock *MockIRoundManager) ScheduleRound(ctx context.Context, r *Round) *time.Time {
	ret := _mock.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for ScheduleRound")
	}

	var r0 *time.Time
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Round) *time.Time); ok {
		r0 = returnFunc(ctx, r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*time.Time)
		}
	}
	return r0
}

// MockIRoundManager_ScheduleRound_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ScheduleRound'
type MockIRoundManager_ScheduleRound_Call struct {
	*mock.Call
}

// ScheduleRound is a helper method to define mock.On call
//   - ctx context.Context
//   - r *Round
func (_e *MockIRoundManager_Expecter) ScheduleRound(ctx interface{}, r interface{}) *MockIRoundManager_ScheduleRound_Call {
	return &MockIRoundManager_ScheduleRound_Call{Call: _e.mock.On("ScheduleRound", ctx, r)}
}

func (_c *MockIRoundManager_ScheduleRound_Call) Run(run func(ctx context.Context, r *Round)) *MockIRoundManager_ScheduleRound_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Round
		if args[1] != nil {
			arg1 = args[1].(*Round)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIRoundManager_ScheduleRound_Call) Return(time1 *time.Time) *MockIRoundManager_ScheduleRound_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *MockIRoundManager_ScheduleRound_Call) RunAndReturn(run func(ctx context.Context, r *Round) *time.Time) *MockIRoundManager_ScheduleRound_Call {
	_c.Call.Return(run)
	return _c
}
